# Generated by Django 4.0.1 on 2023-03-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjimon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('langId', models.IntegerField()),
                ('transcription', models.CharField(max_length=255)),
            ],
        ),
    ]
