# Generated by Django 4.0.1 on 2023-03-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjimon', '0004_translation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lugat',
        ),
        migrations.AlterField(
            model_name='words',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='words',
            name='transcription',
            field=models.CharField(max_length=255, verbose_name='transcription'),
        ),
    ]
